[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "malign"
dynamic = ["version"]
description = "An Open-Source Molecular Alignment Tool"
readme = "README.md"
license = "LICENSE"
authors = [
    { name = "Heliton Martins Reis Filho", email = "helitonmrf@gmail.com" },
]
dependencies = [
    "numpy",
    "PySide6",
    "rdkit",
]

[project.urls]
Homepage = "https://github.com/hellmrf/malign"

[tool.hatch.version]
path = "malign/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/malign",
]

